
on:
 push:
  branches: ["main"]

jobs: 
  download-render-deploy:
    runs-on: ubuntu-latest
    environment: Andmed
    steps:
    - name: Checkpout repo
      uses: actions/checkout@v2
    
    - name: Install Minio client
      run: |
       wget https://dl.min.io/client/mc/release/linux-amd64/mc
       chmod +x mc
       sudo mv mc /usr/local/bin
    
    - name: Configure Minio client
      shell: bash
      env:
       HOST: ${{ secrets.GRIPIRADAR_HOST }}
       ACCESS_KEY: ${{ secrets.GRIPIRADAR_ACCESS_KEY }}
       SECRET_KEY: ${{ secrets.GRIPIRADAR_SECRET_KEY }}
      run: |
       mc alias set myminio $HOST $ACCESS_KEY $SECRET_KEY
    
    - name: Downloaad data from bucket
      run: |
       mc cp --recursive myminio/gripiradar-ut-ee ./
    
    - name: Pull image
      run: |
       docker pull taavipall/gripiradar:latest

    - name: Run quarto
      run: |
       docker run -v $(pwd):/workspace -w /workspace taavipall/gripiradar \
        quarto render index.qmd --output-dir distr
       
    - name: Init new repo in build folder and commit generated files
      run: |
        cd distr
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./distr
