on:
 push:
  branches: ["main"]

permissions:
 contents: read
 pages: write
 id-token: write

concurrency:
 group: "pages"
 cancel-in-progress: false

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: Andmed
    steps:
    - name: Checkpout repo
      uses: actions/checkout@v2
    
    - name: Install Minio client
      run: |
       wget https://dl.min.io/client/mc/release/linux-amd64/mc
       chmod +x mc
       sudo mv mc /usr/local/bin
    
    - name: Configure Minio client
      shell: bash
      env:
       HOST: ${{ secrets.GRIPIRADAR_HOST }}
       ACCESS_KEY: ${{ secrets.GRIPIRADAR_ACCESS_KEY }}
       SECRET_KEY: ${{ secrets.GRIPIRADAR_SECRET_KEY }}
      run: |
       mc alias set myminio $HOST $ACCESS_KEY $SECRET_KEY
    
    - name: Downloaad data from bucket
      run: |
       mc cp --recursive myminio/gripiradar-ut-ee ./
    
    - name: Pull image
      run: |
       docker pull taavipall/gripiradar:latest

    - name: Run quarto
      run: |
       docker run -v $(pwd):/workspace -w /workspace taavipall/gripiradar \
        quarto render index.qmd --output-dir public
     
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
       path: 'public'

 deploy:
  needs: build

  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}

  runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
